name: magenta
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pandas
  - numpy
  - requests
  - tqdm
  - biopython
  - pyyaml
  - fastqc
  - megahit
  - spades
  - pip
  - pip:
      - jupyter
