name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
      - name: Lint
        run: |
          black --check .
          flake8 .

  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Smoke test scripts show help
        run: |
          for f in scripts/*.py; do
            python "$f" --help || true
          done
